export const productsMocks = [
  {
    docID: "3VW3hkio2YLt0REe9nhn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 1",
      color: "Negro",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto1.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "42",
          stock: 3,
        },
      ],
      stockTotal: 3,
      precioVenta: 1200,
      descEfectPorc: 15,
      esPrecioVentaDeGrupo: false,
      IDgrupoDeValores: 2,
      productosRelacionados: [],
      enOferta: true,
      porcentajeDescuentoOferta: 30,
      valoraciones: [],
      codigoNro: "AA00001",
      precioCompra: "800",
      nombre: "Zapato Modelo 1",
      publicado: true,
      detalle: "Zapato de caballero, color negro.",
    },
  },
  {
    docID: "4BX5jmkd2LQr1REf9fhn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 2",
      color: "Marrón",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto2.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "43",
          stock: 5,
        },
      ],
      stockTotal: 5,
      precioVenta: 1350,
      descEfectPorc: 10,
      esPrecioVentaDeGrupo: true,
      IDgrupoDeValores: 1,
      productosRelacionados: [],
      enOferta: false,
      porcentajeDescuentoOferta: 0,
      valoraciones: [],
      codigoNro: "AA00002",
      precioCompra: "900",
      nombre: "Zapato Modelo 2",
      publicado: true,
      detalle: "Zapato de caballero, color marrón.",
    },
  },
  {
    docID: "5VY4jhf2KLd0TEh7nhbn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 3",
      color: "Azul",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto3.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "41",
          stock: 2,
        },
      ],
      stockTotal: 2,
      precioVenta: 1400,
      descEfectPorc: 12,
      esPrecioVentaDeGrupo: true,
      IDgrupoDeValores: 3,
      productosRelacionados: [],
      enOferta: true,
      porcentajeDescuentoOferta: 20,
      valoraciones: [],
      codigoNro: "AA00003",
      precioCompra: "1000",
      nombre: "Zapato Modelo 3",
      publicado: true,
      detalle: "Zapato de caballero, color azul.",
    },
  },
  {
    docID: "6XZ8lkdo1NRw7YIh4phn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 4",
      color: "Beige",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto4.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "40",
          stock: 1,
        },
      ],
      stockTotal: 1,
      precioVenta: 1250,
      descEfectPorc: 20,
      esPrecioVentaDeGrupo: false,
      IDgrupoDeValores: 4,
      productosRelacionados: [],
      enOferta: true,
      porcentajeDescuentoOferta: 25,
      valoraciones: [],
      codigoNro: "AA00004",
      precioCompra: "950",
      nombre: "Zapato Modelo 4",
      publicado: true,
      detalle: "Zapato de caballero, color beige.",
    },
  },
  {
    docID: "7HY5jdkf2MQx0TEi9whn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 5",
      color: "Gris",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto5.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "44",
          stock: 7,
        },
      ],
      stockTotal: 7,
      precioVenta: 1600,
      descEfectPorc: 8,
      esPrecioVentaDeGrupo: false,
      IDgrupoDeValores: 2,
      productosRelacionados: [],
      enOferta: false,
      porcentajeDescuentoOferta: 0,
      valoraciones: [],
      codigoNro: "AA00005",
      precioCompra: "1100",
      nombre: "Zapato Modelo 5",
      publicado: true,
      detalle: "Zapato de caballero, color gris.",
    },
  },
  {
    docID: "8WR4opfo2KPw0TNi4nhn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 6",
      color: "Blanco",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto6.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "45",
          stock: 6,
        },
      ],
      stockTotal: 6,
      precioVenta: 1750,
      descEfectPorc: 10,
      esPrecioVentaDeGrupo: true,
      IDgrupoDeValores: 1,
      productosRelacionados: [],
      enOferta: true,
      porcentajeDescuentoOferta: 15,
      valoraciones: [],
      codigoNro: "AA00006",
      precioCompra: "1200",
      nombre: "Zapato Modelo 6",
      publicado: true,
      detalle: "Zapato de caballero, color blanco.",
    },
  },
  {
    docID: "9DT3qgjf3XQe5UHi6phn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 7",
      color: "Rojo",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto7.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "42",
          stock: 4,
        },
      ],
      stockTotal: 4,
      precioVenta: 1500,
      descEfectPorc: 18,
      esPrecioVentaDeGrupo: true,
      IDgrupoDeValores: 2,
      productosRelacionados: [],
      enOferta: false,
      porcentajeDescuentoOferta: 0,
      valoraciones: [],
      codigoNro: "AA00007",
      precioCompra: "1000",
      nombre: "Zapato Modelo 7",
      publicado: true,
      detalle: "Zapato de caballero, color rojo.",
    },
  },
  {
    docID: "10WQ8sjf3DLr1UJo8lhh",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 8",
      color: "Verde",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto8.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "41",
          stock: 2,
        },
      ],
      stockTotal: 2,
      precioVenta: 1400,
      descEfectPorc: 15,
      esPrecioVentaDeGrupo: false,
      IDgrupoDeValores: 3,
      productosRelacionados: [],
      enOferta: true,
      porcentajeDescuentoOferta: 10,
      valoraciones: [],
      codigoNro: "AA00008",
      precioCompra: "950",
      nombre: "Zapato Modelo 8",
      publicado: true,
      detalle: "Zapato de caballero, color verde.",
    },
  },
  {
    docID: "11OP9dif2XRq0TMi9khn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 9",
      color: "Amarillo",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto9.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "43",
          stock: 5,
        },
      ],
      stockTotal: 5,
      precioVenta: 1550,
      descEfectPorc: 10,
      esPrecioVentaDeGrupo: true,
      IDgrupoDeValores: 2,
      productosRelacionados: [],
      enOferta: true,
      porcentajeDescuentoOferta: 20,
      valoraciones: [],
      codigoNro: "AA00009",
      precioCompra: "1100",
      nombre: "Zapato Modelo 9",
      publicado: true,
      detalle: "Zapato de caballero, color amarillo.",
    },
  },
  {
    docID: "12XU9qljf2LPr9TQi2chn",
    docData: {
      codigoAnterior: "",
      categoria: "Caballeros",
      subcategoria: "Calzado caballeros",
      marca: "Genérico",
      modelo: "Modelo 10",
      color: "Celeste",
      imagen: [
        "https://firebasestorage.googleapis.com/v0/b/iharalondon.appspot.com/o/products%2Fproducto10.png?alt=media",
      ],
      magnitudDisponible: [
        {
          magnitud: "44",
          stock: 3,
        },
      ],
      stockTotal: 3,
      precioVenta: 1700,
      descEfectPorc: 15,
      esPrecioVentaDeGrupo: false,
      IDgrupoDeValores: 1,
      productosRelacionados: [],
      enOferta: false,
      porcentajeDescuentoOferta: 0,
      valoraciones: [],
      codigoNro: "AA00010",
      precioCompra: "1200",
      nombre: "Zapato Modelo 10",
      publicado: true,
      detalle: "Zapato de caballero, color celeste.",
    },
  },
];
